//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Attendance_No { get; set; }
        public System.DateTime Date { get; set; }
        public int DriverNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Check_In_Time { get; set; }
        public System.DateTime Check_Out_Time { get; set; }
    
        public virtual TruckDriver TruckDriver { get; set; }
    }
}
