//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IncID { get; set; }
        public string IncName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public Nullable<byte> Monthly { get; set; }
        public string RecievedFrom { get; set; }
    }
}
