//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STLogisticsEntities : DbContext
    {
        public STLogisticsEntities()
            : base("name=STLogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AreaRates> AreaRates { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Deliveryjob> Deliveryjob { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Fleet> Fleet { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<Quote> Quote { get; set; }
        public virtual DbSet<TruckDriver> TruckDriver { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Breakdowns> Breakdowns { get; set; }
        public virtual DbSet<ArchivedDeliveries> ArchivedDeliveries { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Income> Income { get; set; }
        public virtual DbSet<TransactionTable> TransactionTable { get; set; }
        public virtual DbSet<TrackDelivery> TrackDelivery { get; set; }
        public virtual DbSet<IncompleteDeliveries> IncompleteDeliveries { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<RatingSummary> RatingSummary { get; set; }
    }
}
